baseURL = "https://example.com"
languageCode = "en-us"
title = "KubernetesWeekend"
theme = "yinyang"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]
headTitle = "KubernetesWeekend"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "Github"
link = "https://github.com/fahedouch"